document: badges
SoftEtherVPN/SoftEtherVPN pull request #1227
Opened 2020-10-14 11:07 UTC by xiongnemo

Changes proposed in this pull request:
 - replace old broken GitLab CI badge link (reference: https://docs.gitlab.com/ee/ci/pipelines/settings.html#pipeline-status-badge)
 - adds Azure Pipelines badge for Nightly
 - adds Cirrus CI badge
 - rearrange badges

2020-10-14 17:50 UTC, davidebeatrici requested changes

2020-10-14 17:50 UTC, davidebeatrici commented on README.md
> +|AppVeyor Build status|[![AppVeyor build status](https://ci.appveyor.com/api/projects/status/github/softethervpn/softethervpn?branch=master&svg=true)](https://ci.appveyor.com/project/softethervpn/sof
```suggestion
|AppVeyor|[![AppVeyor build status](https://ci.appveyor.com/api/projects/status/github/softethervpn/softethervpn?branch=master&svg=true)](https://ci.appveyor.com/project/softethervpn/softethervpn) |
```

2020-10-14 17:50 UTC, davidebeatrici commented on README.md
> +|GitLab CI|[![GitLab CI Status](https://gitlab.com/SoftEther/SoftEtherVPN/badges/master/pipeline.svg)](https://gitlab.com/SoftEther/SoftEtherVPN/pipelines)|
```suggestion
|GitLab CI|[![GitLab CI build status](https://gitlab.com/SoftEther/SoftEtherVPN/badges/master/pipeline.svg)](https://gitlab.com/SoftEther/SoftEtherVPN/pipelines)|
```

2020-10-14 17:50 UTC, davidebeatrici commented on README.md
> +|Coverity Scan|[![Coverity Scan Build Status](https://scan.coverity.com/projects/16304/badge.svg)](https://scan.coverity.com/projects/softethervpn-softethervpn)|
```suggestion
|Coverity Scan|[![Coverity Scan build status](https://scan.coverity.com/projects/16304/badge.svg)](https://scan.coverity.com/projects/softethervpn-softethervpn)|
```

2020-10-14 17:50 UTC, davidebeatrici commented on README.md
> +|Azure Piplelines|[![Azure Piplelines Build Status for Nightly](https://dev.azure.com/SoftEther-VPN/SoftEther%20VPN/_apis/build/status/6?api-version=6.0-preview.1)](https://dev.azure.com/SoftEther-VP
```suggestion
|Azure Pipelines[![Azure Pipelines build status for Nightly](https://dev.azure.com/SoftEther-VPN/SoftEther%20VPN/_apis/build/status/6?api-version=6.0-preview.1)](https://dev.azure.com/SoftEther-VPN/SoftEther%20VPN/_build?definitionId=6)|
```

2020-10-14 17:50 UTC, davidebeatrici commented on README.md
> +|Cirrrus CI|[![Build Status](https://api.cirrus-ci.com/github/SoftEtherVPN/SoftEtherVPN.svg)](https://cirrus-ci.com/github/SoftEtherVPN/SoftEtherVPN)|
```suggestion
|Cirrus CI|[![Cirrus CI build status](https://api.cirrus-ci.com/github/SoftEtherVPN/SoftEtherVPN.svg)](https://cirrus-ci.com/github/SoftEtherVPN/SoftEtherVPN)|
```

2020-10-15 02:16 UTC, xiongnemo commented
Misspelling issue resolved ;)

2020-10-15 05:18 UTC, davidebeatrici approved these changes

2020-10-15 05:18 UTC, merged

2020-10-15 05:18 UTC, davidebeatrici commented
Thank you very much for your contribution!