Support more EAP methods for RADIUS auth
SoftEtherVPN/SoftEtherVPN pull request #1775
Opened 2023-02-25 07:43 UTC by domosekai

Changes proposed in this pull request:
- Support EAP and PEAP for SEVPN clients (requires no change on the client side)
   A wrapper is created for SEVPN authentication that reuses the existing EAP / PEAP client for PPP sessions.
- Support all EAP methods (as long as supported by Radius server) for EAP-capable PPP clients
  In other words, we act like a EAP proxy in this case, forwarding EAP packets back and forth.
- Fix the issue that EAP ID may not match incoming Radius challenges
- Fix the issue that clients may get authenticated twice if both the exact user and the asterisk user exist on a hub
  Now we match user twice (exact -> *) but only authenticate once. Authenticate twice can lead to a deadlock for EAP clients.

No changes in UI and vpncmd yet.

EAP and PEAP switch for Radius servers remain unchanged. That is, `RadiusConvertAllMsChapv2AuthRequestToEap` and `RadiusUsePeapInsteadOfEap`.

2023-04-12 00:34 UTC, Evengard requested changes
It mostly LGTM in the PPP stack, except the sending of response without the BEFORE_AUTH state

2023-04-12 00:34 UTC, Evengard commented on src/Cedar/Proto_PPP.c
> +					break;
This block of code is better placed at line 245, setting PPP_STATUS_BEFORE_AUTH here only.
Now, is there a way to delay the first Radius response to a later date?

2023-04-14 13:16 UTC, domosekai commented
As we are not doing EAP ourselves, why is setting PPP_STATUS_BEFORE_AUTH needed?

> It mostly LGTM in the PPP stack, except the sending of response without the BEFORE_AUTH state

2023-04-14 13:19 UTC, Evengard commented
Because we're transitioning from the Connected state to the actual authentication layer. There may be some things which are still being sent for the time being in the Connected state, so we need to make way for them first, and delay the transition to the auth states to another tick.

2023-08-06 17:50 UTC, merged